# This is a basic workflow to help you get started with Actions

name: Linux Image Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Build the Linux Container
        run: docker build -t atf-headless-runner .

      - name: Init Docker Swarm
        run: docker swarm init

      - name: Create the Docker Secret
        run: |
          echo "${{ secrets.TESTING_INSTANCE_PASSWORD }}" | docker secret create sn_password -

      - name: Chrome Test
        run: |
          ./test.sh $URL ${{ secrets.TESTING_INSTANCE_PASSWORD }} headlesschrome Chrome Linux
        env:
          URL: https://atfheadlessrunner.service-now.com

      - name: Firefox Test
        run: |
          ./test.sh $URL ${{ secrets.TESTING_INSTANCE_PASSWORD }} headlessfirefox Firefox Linux
        env:
          URL: https://atfheadlessrunner.service-now.com

      - name: Remove Docker secrets
        if: always()
        run: docker secret rm sn_password








