# This is a basic workflow to help you get started with Actions

name: Windows Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build the Image
        run: docker build -f Dockerfile.windows -t atf-headless-runner:latest .

      # - name: Init Docker Swarm
      #   run: docker swarm init --advertise-addr 127.0.0.1

      # - name: Create the Docker Secret
      #   run: |
      #     echo ${{ secrets.TESTING_INSTANCE_PASSWORD }} | docker secret create sn_password -

      # - name: Install python dependencies
      #   run: |
      #     python -m pip install six
      #     python -m pip install docker
      #     python -m pip install requests

      # - name: Chrome Test
      #   run: python test.py ${{ env.URL }} ${{ secrets.TESTING_INSTANCE_PASSWORD }} headlesschrome Chrome Windows
      #   env:
      #     URL: https://atfheadlessrunner.service-now.com
